name: Sydhavnsfestivalen2016
favicon: null
layout_spectrum: 0.24981
typography_spectrum: 0
title: SYDHAVNSFESTIVALEN 2016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#86a898'
    - '#001f4d'
    - '#61081a'
    - '#f6fd4a'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
