name: Sydhavnsfestivalen2016
favicon: null
layout_spectrum: 0.4089822170790285
typography_spectrum: 0.09649532195180655
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6707780773285776
  lightness: 0.12444836390204728
  saturation: 0.755262958817184
  rhythmicContrast: 0.17411989718675613
purpose: []
